INSERT INTO teams (name, stadium, head_coach, conference, division, active) VALUES
('Buffalo Bills', 'Ralph Wilson Stadium', 'Doug Marrone', 'AFC', 'East', true),
('Miami Dolphins', 'Sun Life Stadium', 'Joe Philbin', 'AFC', 'East', true),
('New England Patriots', 'Gillette Stadium', 'Bill Belichick', 'AFC', 'East', true),
('New York Jets', 'MetLife Stadium', 'Rex Ryan', 'AFC', 'East', true),
('Baltimore Ravens', 'M&T Bank Stadium', 'John Harbaugh', 'AFC', 'North', true),
('Cincinnati Bengals', 'Paul Brown Stadium', 'Marvin Lewis', 'AFC', 'North', true),
('Cleveland Browns', 'FirstEnergy Stadium', 'Mike Pettine', 'AFC', 'North', true),
('Pittsburgh Steelers', 'Heinz Field', 'Mike Tomlin', 'AFC', 'North', true),
('Houston Texans', 'NRG Stadium', 'Bill OBrien', 'AFC', 'South', true),
('Indianapolis Colts', 'Lucas Oil Stadium', 'Chuck Pagano', 'AFC', 'South', true),
('Jacksonville Jaguars', 'EverBank Field', 'Gus Bradley', 'AFC', 'South', true),
('Tennessee Titans', 'LP Field', 'Ken Whisenhunt', 'AFC', 'South', true),
('Denver Broncos', 'Sports Authority Field', 'John Fox', 'AFC', 'West', true),
('Kansas City Chiefs', 'Arrowhead Stadium', 'Andy Reid', 'AFC', 'West', true),
('Oakland Raiders', 'O.co Coliseum', 'Tony Sparano', 'AFC', 'West', true),
('San Diego Chargers', 'Qualcomm Stadium', 'Mike McCoy', 'AFC', 'West', true),
('Dallas Cowboys', 'AT&T Stadium', 'Jason Garrett', 'NFC', 'East', true),
('New York Giants', 'MetLife Stadium', 'Tom Coughlin', 'NFC', 'East', true),
('Philadelphia Eagles', 'Lincoln Financial Field', 'Chip Kelly', 'NFC', 'East', true),
('Washington Redskins', 'FedExField', 'Jay Gruden', 'NFC', 'East', true),
('Chicago Bears', 'Soldier Field', 'Marc Trestman', 'NFC', 'North', true),
('Detroit Lions', 'Ford Field', 'Jim Caldwell', 'NFC', 'North', true),
('Green Bay Packers', 'Lambeau Field', 'Mike McCarthy', 'NFC', 'North', true),
('Minnesota Vikings', 'TCF Bank Stadium', 'Mike Zimmer', 'NFC', 'North', true),
('Atlanta Falcons', 'Georgia Dome', 'Mike Smith', 'NFC', 'South', true),
('Carolina Panthers', 'Bank of America Stadium', 'Ron Rivera', 'NFC', 'South', true),
('New Orleans Saints', 'Mercedes-Benz Superdome', 'Sean Payton', 'NFC', 'South', true),
('Tampa Bay Buccaneers', 'Raymond James Stadium', 'Lovie Smith', 'NFC', 'South', true),
('Arizona Cardinals', 'University of Phoenix Stadium', 'Bruce Arians', 'NFC', 'West', true),
('St. Louis Rams', 'Edward Jones Dome', 'Jeff Fisher', 'NFC', 'West', true),
('San Francisco 49ers', 'Levis Stadium', 'Jim Harbaugh', 'NFC', 'West', true),
('Seattle Seahawks', 'CenturyLink Field', 'Pete Carroll', 'NFC', 'West', true);